-- MySQL Script generated by MySQL Workbench
-- Mon Feb  5 10:57:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema chess_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chess_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chess_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema train_info
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema train_info
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `train_info` ;
USE `chess_db` ;

-- -----------------------------------------------------
-- Table `chess_db`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chess_db`.`role` (
                                                 `id` INT NOT NULL AUTO_INCREMENT,
                                                 `name` VARCHAR(45) NULL DEFAULT 'null',
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 3
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chess_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chess_db`.`user` (
                                                 `id` INT NOT NULL AUTO_INCREMENT,
                                                 `first_name` VARCHAR(45) NOT NULL,
    `last_name` VARCHAR(45) NOT NULL,
    `email` VARCHAR(45) NOT NULL,
    `password` VARCHAR(70) NOT NULL,
    `enabled` TINYINT NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 5
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chess_db`.`users_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chess_db`.`users_roles` (
                                                        `user_id` INT NOT NULL,
                                                        `role_id` INT NOT NULL,
                                                        PRIMARY KEY (`user_id`, `role_id`),
    INDEX `role_id` (`role_id` ASC) VISIBLE,
    CONSTRAINT `role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `train_info`.`role` (`id`),
    CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `chess_db`.`user` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

USE `train_info` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
